- name: Add gen3 helm repo
  become: no
  command: helm repo add gen3 https://helm.gen3.org
  register: helm_repo_add_gen3
  changed_when: '"already exists" not in helm_repo_add_gen3.stdout'

- name: Update helm repos
  become: no
  command: helm repo update gen3
  register: helm_repo_update

- name: Create/update values.yml
  become: no
  tags: values
  template:
    src: values.yml
    dest: "/home/{{ ansible_user }}/values.yml"
    mode: 0600
